# Generated by Django 6.0.3 on 2026-03-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_log_entry', 'Can add log entry')]},
        ),
    ]
