# Generated by Django 6.0.3 on 2026-03-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('log entry', 'Can add log entry')]},
        ),
    ]
