# Generated by Django 6.0.3 on 2026-03-23 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('add_logentry', 'Can add log entry')]},
        ),
    ]
