# Generated by Django 6.0.3 on 2026-03-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_office', 'Can access the manager office')]},
        ),
    ]
